Buildr.settings.build['scala.version'] = "2.10.2"
require 'buildr/scala'

define 'lab1' do
	project.version = '0.0.1'
	package(:jar).with :manifest=>manifest.merge('Main-Class'=>'Main')
	run.using :main => 'Main'
end
